[2024-01-03 11:59:43,136: INFO: main: Welcome to your custom log]
[2024-01-03 19:52:36,784: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-03 19:52:36,803: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-03 19:55:58,097: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-03 19:55:58,100: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-03 19:57:06,928: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-03 19:57:06,929: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-03 19:57:06,931: INFO: common: created directory at: artifacts]
[2024-01-03 19:57:06,934: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-03 19:57:06,936: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1irC6CPtyyBNsoNdnolT7gm08jBbeb0ou/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-03 20:06:51,446: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1irC6CPtyyBNsoNdnolT7gm08jBbeb0ou/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-03 21:20:50,762: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-03 21:20:50,764: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-03 21:20:50,764: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-03 21:20:50,765: INFO: common: created directory at: artifacts]
[2024-01-03 21:20:50,765: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-03 21:20:50,766: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1irC6CPtyyBNsoNdnolT7gm08jBbeb0ou/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-03 21:23:26,612: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-03 21:23:26,614: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-03 21:23:26,614: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-03 21:23:26,615: INFO: common: created directory at: artifacts]
[2024-01-03 21:23:26,616: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-03 21:23:26,616: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1irC6CPtyyBNsoNdnolT7gm08jBbeb0ou/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-03 21:32:09,818: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1irC6CPtyyBNsoNdnolT7gm08jBbeb0ou/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-03 21:34:58,839: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-04 02:44:19,520: INFO: main: *******************]
[2024-01-04 02:44:19,520: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-01-04 02:44:19,523: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 02:44:19,525: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-04 02:44:19,525: INFO: common: created directory at: artifacts]
[2024-01-04 02:44:19,526: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-04 02:44:51,620: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-04 02:44:52,011: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-01-04 03:07:22,840: INFO: main: *******************]
[2024-01-04 03:07:22,841: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-04 03:07:22,845: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-04 03:07:22,846: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-04 03:07:22,847: INFO: common: created directory at: artifacts]
[2024-01-04 03:07:22,848: INFO: common: created directory at: artifacts\training]
[2024-01-05 03:36:48,096: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-05 03:36:48,105: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-05 03:36:48,107: INFO: common: created directory at: artifacts]
[2024-01-05 03:36:48,110: INFO: common: created directory at: artifacts\training]
[2024-01-05 03:45:25,531: INFO: main: *******************]
[2024-01-05 03:45:25,531: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-05 03:45:25,534: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-05 03:45:25,535: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-05 03:45:25,536: INFO: common: created directory at: artifacts]
[2024-01-05 03:45:25,537: INFO: common: created directory at: artifacts\training]
[2024-01-05 03:45:26,662: ERROR: main: weight_decay is not a valid argument, kwargs should be empty  for `optimizer_experimental.Optimizer`.]
Traceback (most recent call last):
  File "C:\Users\kunjd\OneDrive\Desktop\AIML_Project\Kidney_Disease_Prediction\main.py", line 42, in <module>
    model_trainer.main()
  File "c:\users\kunjd\onedrive\desktop\aiml_project\kidney_disease_prediction\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.get_base_model()
  File "c:\users\kunjd\onedrive\desktop\aiml_project\kidney_disease_prediction\src\cnnClassifier\components\model_training.py", line 16, in get_base_model
    self.model = tf.keras.models.load_model(
  File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer_experimental\optimizer.py", line 115, in _process_kwargs
    raise TypeError(
TypeError: weight_decay is not a valid argument, kwargs should be empty  for `optimizer_experimental.Optimizer`.
[2024-01-05 03:53:08,406: INFO: main: *******************]
[2024-01-05 03:53:08,406: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-05 03:53:08,408: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-05 03:53:08,410: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-05 03:53:08,411: INFO: common: created directory at: artifacts]
[2024-01-05 03:53:08,411: INFO: common: created directory at: artifacts\training]
[2024-01-05 03:53:10,694: ERROR: main: You must compile your model before training/testing. Use `model.compile(optimizer, loss)`.]
Traceback (most recent call last):
  File "C:\Users\kunjd\OneDrive\Desktop\AIML_Project\Kidney_Disease_Prediction\main.py", line 42, in <module>
    model_trainer.main()
  File "c:\users\kunjd\onedrive\desktop\aiml_project\kidney_disease_prediction\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
    training.train()
  File "c:\users\kunjd\onedrive\desktop\aiml_project\kidney_disease_prediction\src\cnnClassifier\components\model_training.py", line 76, in train
    self.model.fit(
  File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 3618, in _assert_compile_was_called
    raise RuntimeError(
RuntimeError: You must compile your model before training/testing. Use `model.compile(optimizer, loss)`.
[2024-01-05 03:58:04,084: INFO: main: *******************]
[2024-01-05 03:58:04,084: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-05 03:58:04,087: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-05 03:58:04,089: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-05 03:58:04,090: INFO: common: created directory at: artifacts]
[2024-01-05 03:58:04,090: INFO: common: created directory at: artifacts\training]
[2024-01-05 03:58:05,529: ERROR: main: weight_decay is not a valid argument, kwargs should be empty  for `optimizer_experimental.Optimizer`.]
Traceback (most recent call last):
  File "C:\Users\kunjd\OneDrive\Desktop\AIML_Project\Kidney_Disease_Prediction\main.py", line 42, in <module>
    model_trainer.main()
  File "c:\users\kunjd\onedrive\desktop\aiml_project\kidney_disease_prediction\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.get_base_model()
  File "c:\users\kunjd\onedrive\desktop\aiml_project\kidney_disease_prediction\src\cnnClassifier\components\model_training.py", line 16, in get_base_model
    self.model = tf.keras.models.load_model(
  File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer_experimental\optimizer.py", line 115, in _process_kwargs
    raise TypeError(
TypeError: weight_decay is not a valid argument, kwargs should be empty  for `optimizer_experimental.Optimizer`.
[2024-01-05 03:58:26,401: INFO: main: *******************]
[2024-01-05 03:58:26,402: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-05 03:58:26,404: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-05 03:58:26,405: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-05 03:58:26,406: INFO: common: created directory at: artifacts]
[2024-01-05 03:58:26,406: INFO: common: created directory at: artifacts\training]
[2024-01-05 03:58:28,358: ERROR: main: You must compile your model before training/testing. Use `model.compile(optimizer, loss)`.]
Traceback (most recent call last):
  File "C:\Users\kunjd\OneDrive\Desktop\AIML_Project\Kidney_Disease_Prediction\main.py", line 42, in <module>
    model_trainer.main()
  File "c:\users\kunjd\onedrive\desktop\aiml_project\kidney_disease_prediction\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
    training.train()
  File "c:\users\kunjd\onedrive\desktop\aiml_project\kidney_disease_prediction\src\cnnClassifier\components\model_training.py", line 76, in train
    self.model.fit(
  File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 3618, in _assert_compile_was_called
    raise RuntimeError(
RuntimeError: You must compile your model before training/testing. Use `model.compile(optimizer, loss)`.
[2024-01-05 03:58:52,498: INFO: main: *******************]
[2024-01-05 03:58:52,498: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-05 03:58:52,500: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-05 03:58:52,501: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-05 03:58:52,502: INFO: common: created directory at: artifacts]
[2024-01-05 03:58:52,504: INFO: common: created directory at: artifacts\training]
[2024-01-05 03:58:55,609: ERROR: main: You must compile your model before training/testing. Use `model.compile(optimizer, loss)`.]
Traceback (most recent call last):
  File "C:\Users\kunjd\OneDrive\Desktop\AIML_Project\Kidney_Disease_Prediction\main.py", line 42, in <module>
    model_trainer.main()
  File "c:\users\kunjd\onedrive\desktop\aiml_project\kidney_disease_prediction\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
    training.train()
  File "c:\users\kunjd\onedrive\desktop\aiml_project\kidney_disease_prediction\src\cnnClassifier\components\model_training.py", line 76, in train
    self.model.fit(
  File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 3618, in _assert_compile_was_called
    raise RuntimeError(
RuntimeError: You must compile your model before training/testing. Use `model.compile(optimizer, loss)`.
[2024-01-05 18:22:37,128: INFO: main: *******************]
[2024-01-05 18:22:37,129: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-05 18:22:37,131: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-05 18:22:37,135: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-05 18:22:37,136: INFO: common: created directory at: artifacts]
[2024-01-05 18:22:37,137: INFO: common: created directory at: artifacts\training]
[2024-01-05 18:22:40,955: ERROR: main: You must compile your model before training/testing. Use `model.compile(optimizer, loss)`.]
Traceback (most recent call last):
  File "C:\Users\kunjd\OneDrive\Desktop\AIML_Project\Kidney_Disease_Prediction\main.py", line 42, in <module>
    model_trainer.main()
  File "c:\users\kunjd\onedrive\desktop\aiml_project\kidney_disease_prediction\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
    training.train()
  File "c:\users\kunjd\onedrive\desktop\aiml_project\kidney_disease_prediction\src\cnnClassifier\components\model_training.py", line 76, in train
    self.model.fit(
  File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 3618, in _assert_compile_was_called
    raise RuntimeError(
RuntimeError: You must compile your model before training/testing. Use `model.compile(optimizer, loss)`.
[2024-01-05 18:23:24,558: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-05 18:23:24,563: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-05 18:23:24,565: INFO: common: created directory at: artifacts]
[2024-01-05 18:23:24,568: INFO: common: created directory at: artifacts\training]
[2024-01-05 18:32:55,360: INFO: main: *******************]
[2024-01-05 18:32:55,360: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-05 18:32:55,363: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-05 18:32:55,366: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-05 18:32:55,367: INFO: common: created directory at: artifacts]
[2024-01-05 18:32:55,368: INFO: common: created directory at: artifacts\training]
[2024-01-05 19:05:26,381: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-01-07 10:48:45,383: INFO: main: *******************]
[2024-01-07 10:48:45,384: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-07 10:48:45,387: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-07 10:48:45,389: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-07 10:48:45,389: INFO: common: created directory at: artifacts]
[2024-01-07 10:48:45,391: INFO: common: created directory at: artifacts\training]
[2024-01-07 10:48:45,396: ERROR: main: No file or directory found at artifacts\prepare_base_model\base_model_updated.h5]
Traceback (most recent call last):
  File "C:\Kunj\AIML_Project\Kidney_Disease_Prediction\main.py", line 42, in <module>
    model_trainer.main()
  File "c:\kunj\aiml_project\kidney_disease_prediction\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.get_base_model()
  File "c:\kunj\aiml_project\kidney_disease_prediction\src\cnnClassifier\components\model_training.py", line 16, in get_base_model
    self.model = tf.keras.models.load_model(
  File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\saving\save.py", line 226, in load_model
    raise IOError(
OSError: No file or directory found at artifacts\prepare_base_model\base_model_updated.h5
[2024-01-07 10:49:31,667: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-07 10:49:31,670: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-07 10:49:31,671: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-07 10:49:31,672: INFO: common: created directory at: artifacts]
[2024-01-07 10:49:31,672: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-07 10:49:31,673: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1irC6CPtyyBNsoNdnolT7gm08jBbeb0ou/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-07 11:00:13,619: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1irC6CPtyyBNsoNdnolT7gm08jBbeb0ou/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-07 11:02:02,742: ERROR: main: [Errno 13] Permission denied: 'artifacts\\data_ingestion\\Kidney-Report\\Cyst\\Cyst- (3195).jpg']
Traceback (most recent call last):
  File "C:\Kunj\AIML_Project\Kidney_Disease_Prediction\main.py", line 14, in <module>
    data_ingestion.main()
  File "C:\Kunj\AIML_Project\Kidney_Disease_Prediction\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "C:\Kunj\AIML_Project\Kidney_Disease_Prediction\src\cnnClassifier\components\data_ingestion.py", line 46, in extract_zip_file
    zip_ref.extractall(unzip_path)
  File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'artifacts\\data_ingestion\\Kidney-Report\\Cyst\\Cyst- (3195).jpg'
[2024-01-07 11:25:34,063: INFO: main: *******************]
[2024-01-07 11:25:34,063: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-01-07 11:25:34,065: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-07 11:25:34,070: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-07 11:25:34,072: INFO: common: created directory at: artifacts]
[2024-01-07 11:25:34,073: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-07 11:25:36,691: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-07 11:25:37,663: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-01-07 11:25:37,664: INFO: main: *******************]
[2024-01-07 11:25:37,664: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-07 11:25:37,667: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-07 11:25:37,669: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-07 11:25:37,670: INFO: common: created directory at: artifacts]
[2024-01-07 11:25:37,671: INFO: common: created directory at: artifacts\training]
[2024-01-07 11:26:02,519: ERROR: main: Graph execution error:

Detected at node 'model/block1_conv2/Relu' defined at (most recent call last):
    File "C:\Kunj\AIML_Project\Kidney_Disease_Prediction\main.py", line 42, in <module>
      model_trainer.main()
    File "c:\kunj\aiml_project\kidney_disease_prediction\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
      training.train()
    File "c:\kunj\aiml_project\kidney_disease_prediction\src\cnnClassifier\components\model_training.py", line 81, in train
      self.model.fit(
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1564, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1160, in train_function
      return step_function(self, iterator)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1146, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1135, in run_step
      outputs = model.train_step(data)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 993, in train_step
      y_pred = self(x, training=True)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 557, in __call__
      return super().__call__(*args, **kwargs)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\engine\base_layer.py", line 1097, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\engine\functional.py", line 510, in call
      return self._run_internal_graph(inputs, training=training, mask=mask)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\engine\functional.py", line 667, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\engine\base_layer.py", line 1097, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\layers\convolutional\base_conv.py", line 314, in call
      return self.activation(outputs)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\activations.py", line 317, in relu
      return backend.relu(
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\backend.py", line 5366, in relu
      x = tf.nn.relu(x)
Node: 'model/block1_conv2/Relu'
OOM when allocating tensor with shape[32,64,224,224] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node model/block1_conv2/Relu}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.
 [Op:__inference_train_function_1842]]
Traceback (most recent call last):
  File "C:\Kunj\AIML_Project\Kidney_Disease_Prediction\main.py", line 42, in <module>
    model_trainer.main()
  File "c:\kunj\aiml_project\kidney_disease_prediction\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
    training.train()
  File "c:\kunj\aiml_project\kidney_disease_prediction\src\cnnClassifier\components\model_training.py", line 81, in train
    self.model.fit(
  File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\tensorflow\python\eager\execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.ResourceExhaustedError: Graph execution error:

Detected at node 'model/block1_conv2/Relu' defined at (most recent call last):
    File "C:\Kunj\AIML_Project\Kidney_Disease_Prediction\main.py", line 42, in <module>
      model_trainer.main()
    File "c:\kunj\aiml_project\kidney_disease_prediction\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
      training.train()
    File "c:\kunj\aiml_project\kidney_disease_prediction\src\cnnClassifier\components\model_training.py", line 81, in train
      self.model.fit(
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1564, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1160, in train_function
      return step_function(self, iterator)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1146, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1135, in run_step
      outputs = model.train_step(data)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 993, in train_step
      y_pred = self(x, training=True)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 557, in __call__
      return super().__call__(*args, **kwargs)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\engine\base_layer.py", line 1097, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\engine\functional.py", line 510, in call
      return self._run_internal_graph(inputs, training=training, mask=mask)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\engine\functional.py", line 667, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\engine\base_layer.py", line 1097, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\layers\convolutional\base_conv.py", line 314, in call
      return self.activation(outputs)
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\activations.py", line 317, in relu
      return backend.relu(
    File "C:\Users\kunjd\Anaconda3\envs\kidney\lib\site-packages\keras\backend.py", line 5366, in relu
      x = tf.nn.relu(x)
Node: 'model/block1_conv2/Relu'
OOM when allocating tensor with shape[32,64,224,224] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node model/block1_conv2/Relu}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.
 [Op:__inference_train_function_1842]
[2024-01-07 11:50:17,959: INFO: main: *******************]
[2024-01-07 11:50:17,959: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-07 11:50:17,961: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-07 11:50:17,964: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-07 11:50:17,965: INFO: common: created directory at: artifacts]
[2024-01-07 11:50:17,965: INFO: common: created directory at: artifacts\training]
[2024-01-07 11:51:29,343: INFO: main: *******************]
[2024-01-07 11:51:29,343: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-07 11:51:29,345: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-07 11:51:29,348: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-07 11:51:29,349: INFO: common: created directory at: artifacts]
[2024-01-07 11:51:29,350: INFO: common: created directory at: artifacts\training]
[2024-01-07 11:54:46,593: INFO: main: *******************]
[2024-01-07 11:54:46,593: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-07 11:54:46,595: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-07 11:54:46,596: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-07 11:54:46,597: INFO: common: created directory at: artifacts]
[2024-01-07 11:54:46,597: INFO: common: created directory at: artifacts\training]
[2024-01-07 12:34:23,797: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-01-07 12:38:50,850: INFO: main: *******************]
[2024-01-07 12:38:50,850: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-07 12:38:50,853: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-07 12:38:50,856: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-07 12:38:50,856: INFO: common: created directory at: artifacts]
[2024-01-07 12:38:50,857: INFO: common: created directory at: artifacts\training]
[2024-01-07 15:18:38,506: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-01-07 16:23:10,468: INFO: main: *******************]
[2024-01-07 16:23:10,470: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-01-07 16:23:10,472: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-07 16:23:10,475: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-07 16:23:10,477: INFO: common: created directory at: artifacts]
[2024-01-07 16:24:01,698: INFO: common: json file saved at: scores.json]
[2024-01-07 16:24:01,706: INFO: common: json file saved at: scores.json]
[2024-01-07 16:24:01,712: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-01-07 16:50:27,596: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-07 16:50:27,602: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-07 16:50:27,606: INFO: common: created directory at: artifacts]
[2024-01-07 18:12:09,774: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-07 18:12:09,780: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-07 18:12:09,782: INFO: common: created directory at: artifacts]
[2024-01-07 18:14:39,311: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-07 18:14:39,317: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-07 18:14:39,320: INFO: common: created directory at: artifacts]
